pub mod v1 {
    // This will be replaced by code generated by tonic-build during compilation
    tonic::include_proto!("saasy.sfu.v1");
}

pub use v1::{
    sfu_event,
    sfu_request_envelope,
    sfu_response_envelope,
    ConsumerClosedEvent,
    ConsumerScoreEvent,
    DtlsStateChangeEvent,
    FarewellRequestedEvent,
    IceStateChangeEvent,
    NewProducerEvent,
    ProducerClosedEvent,
    ProducerScoreEvent,
    RegisterSessionRequest,
    SessionCreatedEvent,
    SessionEndedEvent,
    SessionEndReason,
    SfuEvent,
    SfuRequestEnvelope,
    SfuResponseEnvelope,
    SubscriptionConfirmedEvent,
    TransportClosedEvent,
    UsageStatusEvent,
};
pub use v1::sfu_service_server::{
    SfuService,
    SfuServiceServer,
};
pub use v1::sfu_service_client::SfuServiceClient;
