pub mod v1 {
    // This will be replaced by code generated by tonic-build during compilation
    tonic::include_proto!("saasy.signal.v1");
}

pub use v1::{
    signal_request_envelope,
    signal_response_envelope,
    RegisterSessionRequest,
    SignalRequestEnvelope,
    SignalResponseEnvelope,
};
pub use v1::signal_service_server::{
    SignalService,
    SignalServiceServer,
};
pub use v1::signal_service_client::SignalServiceClient;
